---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu-webcounter-virtualbox
    driver:
      box: ubuntu-webcounter-virtualbox-test
      box_url: file:///<%= ENV['PWD'] %>/output-webcounter-vagrant/package.box
      provider: virtualbox

verifier:
  name: inspec
  sudo: false

suites:
  - name: default
